### PR TITLE
feat: plan page

### PR DESCRIPTION
**Pull request by haydenull**

### CODE REVIEW

**Comment by haydenull** [comment]
> @haydenull, How to open the plan page?

@AnweshGangula 
image

**Comment by AnweshGangula** [comment]
Okay, Thank you.
I don't see a "Tomorrow" column in Plane page though.

The "2023-11-19" changelog in [Notion](https://haydenut.notion.site/Changelog-ff900b4119874913ab7485ff894cfc45) mentions you added "Tomorrow" column

**Comment by AnweshGangula** [comment]
Okay, looks like the "Tomorrow" column is only visible if I click on "Plan" on the Tomorrow Dat column in "Tasks" View

**Comment by haydenull** [comment]
> Okay, looks like the "Tomorrow" column is only visible if I click on "Plan" on the Tomorrow Dat column in "Tasks" View

Yes, the reason for designing it this way is that some people are accustomed to planning their tasks for tomorrow at the end of today, while others are accustomed to planning their tasks at the beginning of the day.

**Pull request merged**
